#!/usr/bin/env python3
"""The Evo font: symce/font/{large,small}.txt -> symce/obj/font.inc.

    mkfont.py            self-check (also `check`; make -C symce check runs it)
    mkfont.py build      the .txt files -> obj/font.inc, which app/main.asm includes
    mkfont.py seed small|large   ONE-OFF: rewrite ONE .txt file from Roboto (needs Pillow,
                         the Roboto variable TTF, and the calculator ROM for the
                         advance widths; the ROM is only read, nothing of it is kept)

The .txt files are the source of truth and are hand-edited. One block per glyph:

    == 0x41 A          display glyph index (NOT a token), then a label
    ..####..           rows of . and #

LARGE (large.txt, the font hook): 12 columns x 14 rows, always. Stored as the OS
wants it, 28 bytes: per row byte 0 = columns 0-4 in bits 7..3, byte 1 = columns
5-11 in bits 7..1.
SMALL (small.txt, the localize hook): as wide as the glyph's advance -- the same
as TI's, so no screen layout moves. Stored as 25 bytes: the width, then 14 rows
of 1 byte (width <= 8, MSB = left column) or 12 rows of 2 bytes (width > 8:
columns 0-7, then 8.. from the MSB of byte 1), zero-padded.

A glyph in neither file is drawn by the OS as TI's; both files cover the same
indices, which font.inc maps through one 256-byte table: 0 = not ours, else the
record number (1-based) in each font's table.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'symce', 'font')
OUT = os.path.join(ROOT, 'symce', 'obj', 'font.inc')
ROM = os.environ.get('AUTOTESTER_ROM') or os.path.expanduser('~/CEdev/ti84pce.rom')
TTF = os.environ.get('ROBOTO_TTF', '/tmp/claude-501/evofont/Roboto-var.ttf')

LW, LH = 12, 14
# Covered display glyph indices: ASCII 0x21..0x7E (0x5B is theta here, not '['),
# and ² ³ ≤ ≠ ≥ → π.
EXTRA = {0x12: '²', 0xD5: '³', 0x17: '≤', 0x18: '≠', 0x19: '≥', 0x1C: '→', 0xC4: 'π'}
CODES = list(range(0x21, 0x7F)) + sorted(EXTRA)
LABEL = {**{c: chr(c) for c in range(0x21, 0x7F)}, 0x5B: 'θ', **EXTRA}
CODES.sort()


def rows_small(w):
    return 14 if w <= 8 else 12


def parse(path):
    """{code: [row, ...]} in file order; no duplicates, uniform rows."""
    out, cur = {}, None
    for n, line in enumerate(open(path, encoding='utf-8'), 1):
        line = line.rstrip()
        if line.startswith('=='):
            code = int(line.split()[1], 16)
            assert code not in out, '%s:%d duplicate glyph 0x%02X' % (path, n, code)
            cur = out[code] = []
        elif line:
            assert cur is not None and set(line) <= set('.#'), '%s:%d bad row' % (path, n)
            cur.append(line)
    return out


def pack_large(rows):
    assert len(rows) == LH and all(len(r) == LW for r in rows), 'large glyph is 12x14'
    out = bytearray()
    for r in rows:
        v = int(r.replace('.', '0').replace('#', '1'), 2)          # 12 bits, column 0 = bit 11
        out += bytes([(v >> 7) << 3 & 0xFF, (v & 0x7F) << 1])
    return bytes(out)


def unpack_large(b):
    return [''.join('#' if (b[2 * r] >> (7 - i) if i < 5 else b[2 * r + 1] >> (12 - i)) & 1 else '.'
                    for i in range(LW)) for r in range(LH)]


def pack_small(rows):
    w = len(rows[0])
    assert 1 <= w <= 16 and len(rows) == rows_small(w) and all(len(r) == w for r in rows), \
        'small glyph: width 1..16, %d rows' % rows_small(w)
    out = bytearray([w])
    for r in rows:
        v = int(r.replace('.', '0').replace('#', '1'), 2) << (8 * (1 if w <= 8 else 2) - w)
        out += v.to_bytes(1 if w <= 8 else 2, 'big')
    return bytes(out).ljust(25, b'\0')


def unpack_small(b):
    w, k = b[0], 1 if b[0] <= 8 else 2
    return [''.join('#' if (int.from_bytes(b[1 + r * k:1 + (r + 1) * k], 'big') >> (8 * k - 1 - i)) & 1 else '.'
                    for i in range(w)) for r in range(rows_small(w))]


def load():
    """(large, small): {code: record bytes}, both covering exactly CODES."""
    large = {c: pack_large(r) for c, r in parse(os.path.join(FONT, 'large.txt')).items()}
    small = {c: pack_small(r) for c, r in parse(os.path.join(FONT, 'small.txt')).items()}
    assert sorted(large) == sorted(small) == CODES, \
        'large/small differ from CODES: %s' % sorted(set(large) ^ set(CODES) | set(small) ^ set(CODES))
    return large, small


def build():
    large, small = load()
    slot = {c: i + 1 for i, c in enumerate(CODES)}

    def db(name, data, step):
        return '%s:\n' % name + ''.join('    db %s\n' % ','.join('$%02X' % x for x in data[i:i + step])
                                        for i in range(0, len(data), step))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('; Generated by tools/mkfont.py from symce/font/*.txt. Do not edit.\n')
        f.write(db('font_map', bytes(slot.get(c, 0) for c in range(256)), 16))
        f.write(db('font_large', b''.join(large[c] for c in CODES), 28))
        f.write(db('font_small', b''.join(small[c] for c in CODES), 25))


def check():
    import random
    rnd = random.Random(1)
    for _ in range(300):                               # txt -> bytes -> txt, every shape
        w = rnd.randint(1, 16)
        rows = [''.join(rnd.choice('.#') for _ in range(w)) for _ in range(rows_small(w))]
        b = pack_small(rows)
        assert len(b) == 25 and b[0] == w and unpack_small(b) == rows, rows
        rows = [''.join(rnd.choice('.#') for _ in range(LW)) for _ in range(LH)]
        b = pack_large(rows)
        assert len(b) == 28 and unpack_large(b) == rows, rows
    # The two orders the OS reads: a lone column-0 / column-5 / column-11 pixel.
    assert pack_large(['#' + '.' * 11] + ['.' * 12] * 13)[:2] == b'\x80\x00'
    assert pack_large(['.' * 5 + '#' + '.' * 6] + ['.' * 12] * 13)[:2] == b'\x00\x80'
    assert pack_large(['.' * 11 + '#'] + ['.' * 12] * 13)[:2] == b'\x00\x02'
    assert pack_small(['#.......'] * 14)[:3] == b'\x08\x80\x80'
    assert pack_small(['.' * 8 + '#'] + ['.' * 9] * 11)[:4] == b'\x09\x00\x80\x00'
    large, small = load()                              # the shipped files: sizes, coverage
    assert len(CODES) == len(set(CODES)) and all(len(v) == 28 for v in large.values())
    assert all(len(v) == 25 for v in small.values())
    for c in CODES:
        assert unpack_large(large[c]) == parse(os.path.join(FONT, 'large.txt'))[c]
        assert unpack_small(small[c]) == parse(os.path.join(FONT, 'small.txt'))[c]
    for c in CODES:                                    # the OS crops small text to rows 2..11 (measured)
        rows = unpack_small(small[c])
        assert not any('#' in r for r in rows[:2] + rows[12:]), 'small 0x%02X has ink outside rows 2..11' % c
    for name, tab, un in (('large', large, unpack_large), ('small', small, unpack_small)):
        rows = un(tab[0x2A])                            # '*': mirror-symmetric about its own ink box
        cols = [c for r in rows for c, ch in enumerate(r) if ch == '#']
        lo, hi = min(cols), max(cols)
        assert all(r[lo:hi + 1] == r[lo:hi + 1][::-1] for r in rows), '%s * is lopsided' % name
    build()
    inc = open(OUT).read()
    assert inc.count('    db ') == 16 + len(CODES) + len(CODES), 'font.inc has the wrong number of rows'
    print('mkfont: %d glyphs, large %d B, small %d B, ok' % (len(CODES), 28 * len(CODES), 25 * len(CODES)))


# ---------------------------------------------------------------------------
# seed: one-off, Roboto -> .txt. Hand-edit the .txt afterwards; never rerun this
# over edits.
# ---------------------------------------------------------------------------
SS = 4                        # supersampling, for the glyphs that have to be scaled
# Roboto's pixel size, weight, width axis and the threshold for a scaled glyph; the
# rows ink may use and its baseline row; the x-height row (TI squeezes g p q y into
# the x-height rows plus the descender, so do we).
LARGE_SEED = dict(px=20, wght=400, wdth=100, thr=110, top=0, base=13, xtop=4)
SMALL_SEED = dict(px=14, wght=700, wdth=100, thr=110, top=2, base=11, xtop=4, fit=1)
SQUASH = 'gpqy'               # scaled into xtop..base
DOT = 'j'                     # scaled into top..base


def seed(which):
    from PIL import Image, ImageDraw, ImageFont
    rom = open(ROM, 'rb').read()

    def draw(ch, px, p, mono):
        f = ImageFont.truetype(TTF, px)
        f.set_variation_by_axes([p['wght'], p['wdth']])
        im = Image.new('L', (px * 3, px * 3), 0)
        d = ImageDraw.Draw(im)
        d.fontmode = '1' if mono else 'L'
        d.text((px, 2 * px), ch, font=f, fill=255, anchor='ls')
        bb = im.getbbox()
        return im.crop(bb), bb[1] - 2 * px                # ink, its top relative to the baseline

    def render(code, cellw, rows, p):
        ch, maxw = LABEL[code], max(cellw - 2, 1) if cellw != LW else 10
        lo, hi = p['top'], p['base'] + 1
        for wd in range(p['wdth'], 74 if p.get('fit') else p['wdth'] - 1, -5):   # widest that fits
            p = dict(p, wdth=wd)
            ink, dy = draw(ch, p['px'], p, True)
            w, h = ink.size
            if w <= maxw:
                break
        top = hi + dy
        squash = ch in SQUASH + DOT and code < 0x80
        if squash or top < lo or top + h > hi or w > maxw:  # scale it in
            ink, dy = draw(ch, p['px'] * SS, p, False)
            top, bot = (p['xtop'] if ch in SQUASH else lo), hi
            if not squash:
                top = max(lo, min(hi - 1, hi + dy // SS))
                bot = min(hi, top + round(ink.size[1] / SS)) if top + ink.size[1] / SS <= hi else hi
                top = lo if bot - top < ink.size[1] / SS - .5 else top
            w = min(round(ink.size[0] / SS), maxw)
            ink = ink.resize((w, max(bot - top, 1)), Image.LANCZOS).point(lambda v: 255 if v >= p['thr'] else 0)
            h = bot - top
        else:
            ink = ink.point(lambda v: 255 if v else 0)
        left = (cellw - w) // 2
        out = [['.'] * cellw for _ in range(rows)]
        for y in range(h):
            for x in range(w):
                if ink.getpixel((x, y)):
                    out[top + y][left + x] = '#'
        return [''.join(r) for r in out]

    def write(name, blocks):
        with open(os.path.join(FONT, name), 'w', encoding='utf-8') as f:
            for c in CODES:
                f.write('== 0x%02X %s\n%s\n\n' % (c, LABEL[c], '\n'.join(blocks[c])))
    os.makedirs(FONT, exist_ok=True)
    if which == 'large':
        write('large.txt', {c: render(c, LW, LH, LARGE_SEED) for c in CODES})
    else:
        small = {}
        for c in CODES:
            w = rom[0xA3CA9 + c * 25]                 # TI's advance: kept, so no layout moves
            small[c] = render(c, w, rows_small(w), SMALL_SEED)
        write('small.txt', small)


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'check'
    if cmd == 'seed':
        assert sys.argv[2:] in (['large'], ['small']), 'seed large|small: one font, the other has hand edits'
        seed(sys.argv[2])
    else:
        {'check': check, 'build': build}[cmd]()
