#!/usr/bin/env python3
"""Turn a linked blob into fasmg source whose absolute addresses relocate.

    relocs.py LABEL OUT.inc BASE1 BLOB1 BASE2 BLOB2 BASE3 BLOB3

The same code linked at two bases differs exactly where it holds an absolute
address of itself: those 24-bit words differ by BASE2-BASE1. Every such word is
written as `dl LABEL + offset`, which the app packaging (app.inc) records as a
relocation because it is relative to app.base -- so app_create patches it to
wherever the app lands in flash. Everything else is written as plain bytes.

The deltas are chosen with every byte nonzero, so a relocated word always
differs in its low byte and the scan lines up on it. The third link checks the
result: relocating image 1 to BASE3 must reproduce image 3 byte for byte, or
something in the blob depends on its address in a way this cannot express.
"""
import sys


def main():
    label, out, *rest = sys.argv[1:]
    (b1, f1), (b2, f2), (b3, f3) = [(int(rest[i], 0), rest[i + 1]) for i in (0, 2, 4)]
    img1, img2, img3 = (open(f, 'rb').read() for f in (f1, f2, f3))
    if not len(img1) == len(img2) == len(img3):
        sys.exit('relocs: the three links differ in size')
    delta = (b2 - b1) & 0xFFFFFF

    def word(img, i):
        return int.from_bytes(img[i:i + 3], 'little')

    relocs, i = [], 0
    while i < len(img1):
        if img1[i] == img2[i]:
            i += 1
            continue
        target = word(img1, i) - b1
        if i + 3 > len(img1) or (word(img2, i) - word(img1, i)) & 0xFFFFFF != delta \
                or not 0 <= target <= len(img1):
            sys.exit('relocs: offset %#x differs but is not an address of the blob' % i)
        relocs.append((i, target))
        i += 3

    moved = bytearray(img1)
    for i, target in relocs:
        moved[i:i + 3] = (b3 + target).to_bytes(3, 'little')
    if bytes(moved) != img3:
        sys.exit('relocs: relocating to %#x does not reproduce the third link' % b3)

    lines = ['; Generated by tools/relocs.py -- do not edit.',
             '; %d bytes, %d relocations.' % (len(img1), len(relocs)),
             '%s:' % label]
    pos = 0
    for i, target in relocs + [(len(img1), None)]:
        for j in range(pos, i, 16):
            lines.append('    db ' + ','.join('$%02X' % b for b in img1[j:min(j + 16, i)]))
        if target is not None:
            lines.append('    dl %s + $%04X' % (label, target))
        pos = i + 3
    open(out, 'w').write('\n'.join(lines) + '\n')
    print('relocs: %d bytes, %d relocations, checked at %#x' % (len(img1), len(relocs), b3))


if __name__ == '__main__':
    main()
